### ISSUE TITLE
Failure: Missing/Illegal Combination of Package/Dimensions

### ISSUE THREAD

**Issue by Herokid** [verbb/postie#52]
First of all I wanted to tell you that I tried to ask this question through the support form, but I did not receive a response. Maybe it's because of schedules and countries.
If you have received my email, let me now and I close this issue.

**The error**
[-][1][-][info][postie] UPS: Sending payload: `{"PickupType":{"Code":"01","Description":null},"Shipment":{}}`.
[-][1][-][error][postie] UPS: API error: `Failure: Missing/Illegal Combination of Package/Dimensions (110602):144`
(The error is preceded by a "Sending payload:", where the Shipment field is empty.)

**Description**
I am receiving this message, I have spoken to UPS and they have told me that the measurements I am using (kg and cm) are correct.
The fact is that not all products in the store will be shipped by UPS and in these products I can not specify sizes.
I doubt if this error comes from products that have no measures or if it may be for another reason.

Is it necessary to add measurements on all products?

Thanks in advance.

**Comment by engram-design** [comment]
Can you advise the Postie version you're on? Having multiple items in your cart, with some having no dimensions is totally fine, they'll just not be factored into the shipping boxes for estimation.

But, if you try to complete checkout with **only** products that have no set dimension/weight values, you're going to end up with this sort of error.

If your support email, you mentioned adding exceptions for certain cities - this is achievable through [events](https://verbb.io/craft-plugins/postie/docs/developers/events)

Otherwise, these errors are pretty harmless, as it's expected behaviour. UPS is reporting that the shipment is invalid (there are no items to ship), and therefore can't quote them.

**Comment by Herokid** [comment]
Hi @engram-design 
My Postie version yesterday is 2.3, I just updated to 2.4.2

The last tests I did were only with products that did have dimensions.
Maybe they are harmless messages, but I can never recover any shipping costs, in fact, it does not even list the method I have created in UPS when I iterate the cart methods. (cart.availableShippingMethodOptions).

I am trying to clarify with my client what service and type of collection they usually use with UPS to see if I get a positive result.

Regarding the issue of products and their shipping area, it is a bit more complex as I use a third-party API for a Deliveroo type shipping service, in which the price is calculated according to the distance between two postal addresses.

For this type of shipping I had to create an Adjuster.
I'm not a great development expert on Craft, much less on Commerce. These are hard days for me.

Today, I update Postie to 2.4.2

Thanks for the clarification.
David.

**Comment by engram-design** [comment]
Yep, so the reason I ask is the box-packing mechanism was overhauled in 2.4.x, so we should get **much** results from providers. Indeed, I was testing with the latest version which ignores anything non-dimension defined in the cart for UPS.

Anyway, do let me know if you need a hand, clarification or are not seeing what you expect!

**Comment by Herokid** [comment]
Ok, thanks @engram-design (:
