### ISSUE TITLE
Input variables exceeded 1000

### ISSUE THREAD

**Issue by Herokid** [verbb/postie#54]
**Description**
After update to 2.4.2, i have these error when I try to change any option in Postie tabs.

```
yii\base\ErrorException: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in /MY_PATH/vendor/yiisoft/yii2/base/ErrorException.php:43
Stack trace:
#0 /MY_PATH/vendor/craftcms/cms/bootstrap/web.php(51): require()
#1 /MY_PATH/web/index.php(21): require('/MY_PATH...')
#2 {main}
```

**Steps to reproduce**
1. Enable/Disable Postie
2. Enable/Disable Provider shipping methods
3. Just changing any Postie config value.

**Additional info**
- Plugin version: 2.4.2
- Craft version: 3.5.16
- Multi-site: No

**Additional context**
I fix just changing max_input_vars in my local php.ini, but I'm worried that when I upload it into production I can't make this change.

Thanks in advance.

**Comment by engram-design** [comment]
This is a necessary setting to change at least for the moment. This is due to the additional amount of settings (mostly the box sizes) that have been added. Combined with the number of a new providers as well, and the fact that all providers settings are saved in one go.

You won't need to alter this on production, as you shouldn't be allowing editing settings like Postie's on production if you have `allowAdminChanges = false` (which is probably a good idea). It only really affects saving the plugin settings. It's also a pretty common setting to have to tweak particularly for large Matrix fields.

**Comment by Herokid** [comment]
Ok, again, thanks for the clarification.
