### ISSUE TITLE
Zero weight, zero dimension service add-ons

### ISSUE THREAD

**Issue by terraindesign** [verbb/postie#56]
This may be more of a question than a feature request. Currently my client's store includes add-on customization options for products (custom imprinting, custom inserts, etc), which have zero weight, zero dimensions. These are essentially services which are added to the order as separate line-items. According to the documentation, it sounds like Postie will reject orders/items that do not have weight/dimensions. Is their a work-around for this? Or is there a way to exclude line-items from being included in the shipping calculations? Or have I just interpreted the documentation incorrectly?

If not, I would suggest perhaps just ignoring any items that have zero weight, zero dimensions, rather than rejecting the request/order (or add a preference). I imagine that this use case is quite common, as many store have service items that are not necessarily physical products.

Please advise. Thanks.

**Comment by engram-design** [comment]
So that's correct in that Postie will reject line items with no dimensions and weight - but rejected in such a way that they will be ignored.

So for instance, you might have an order with 5 line items, and 1 of those line items might be a Gift Voucher, one of your described add-on's, or some other virtual line item that doesn't require shipping. The entire order will still be evaluated for shipping rates, but the virtual line item won't be factored in (because it can't).

Where points in the documentation state this requirement, it's more for if those 5 line items were physical products that you want shipped - they all _really_ need dimension/weight values. Again, if you defined these properties for only 1 of the products in your order, you'll only get rate estimates for that single item, which would be extremely inaccurate (by not factoring the 4 other products).

Does that make sense?

**Comment by terraindesign** [comment]
Understood. Thank you. That clarifies things. Much appreciated. Here was the somewhat confusing lines in the docs.

"Specifically, the dimensions and weights for each product must be set up. Without these set, you'll likely get inaccurate results, or none altogether!"

https://verbb.io/craft-plugins/postie/docs/setup-configuration/products
