### ISSUE TITLE
Shipping costs not being added to the cart totals

### ISSUE THREAD

**Issue by ax2000** [verbb/postie#72]
Hi Josh,

After fixing #69, I've come up with another different issue that doesn't appear to be related to that.

The shipping options appear correctly now, but once I select one of the options available, it seems to get added to the cart correctly (` ["shippingMethodHandle"]=> string(18) "AUS_PARCEL_EXPRESS"`) BUT the Shipping costs don't get added to the cart shipping nor to the cart total (`["storedTotalShippingCost"]=> string(6) "0.0000"`).

If I select a native Commerce Shipping Method, the shipping costs get added to the cart as expected, which made me think that I might have missed something with Postie or maybe the latest Commerce updates broke something.

Please see below screenshot as reference:

![Screen Shot 2021-07-21 at 17 13 02](https://user-images.githubusercontent.com/2585959/126446978-c945aac0-c7e3-413d-94c7-7cfbec4c02ec.png)

I just updated to craft commerce dev branch as per #70 so not sure if it would have something to do with that?

**Steps to reproduce**
1. Select shipping method
2. Check cart and shipping costs don't appear under Shipping

**Additional info**
- Plugin version: 2.4.8
- Craft version: 3.7.4
- Craft Commerce: dev-develop#d27edbc38c6946462c4fae2bb6d822f4a0690373 as 3.4.0.2
- Multi-site: No

**Comment by engram-design** [comment]
I'm almost certain a Commerce update has broken this, as I can't get `{{ cart.shippingMethod.name }}` to work anymore either. I've been trying to get in touch with Luke today, but will file a formal GH issue shortly.

I believe this is because a change in behaviour from Commerce 3.3.x to 3.4.x where the shipping methods are only fetching the saved ones created through Commerce, not plugin-provided ones like Postie, or through your own modules.

**Comment by engram-design** [comment]
Should be fixed in [Commerce 3.4.0.3](https://github.com/craftcms/commerce/releases/tag/3.4.0.3) https://github.com/craftcms/commerce/issues/2279

**Comment by angieherrera** [comment]
Hey! I might just be missing something, but I'm running into this exact issue with Craft 4.3.0, Commerce 4.1.3, and Postie 3.0.1. Let me know if I should post to Craft's GH instead.

**Comment by engram-design** [comment]
I can't seem, to replicate that I'm afraid (the price applying). Selecting a shipping option saves the value to the order for me.

![screencapture-commerce4-test-shop-checkout-shipping-2022-10-29-16_15_17](https://user-images.githubusercontent.com/1221575/198815209-cd0eada6-b487-4df8-94b4-83ed6828e7d4.png)

![screencapture-commerce4-test-shop-checkout-payment-method-2022-10-29-16_15_31](https://user-images.githubusercontent.com/1221575/198815207-e8d5b75f-60d0-410d-b1fc-0d441f5d39bd.png)

**However**, what's interesting is that on the payment page its not showing which service was picked. This is because `cart.shippingMethod` is null. Despite `cart.shippingMethodName` being the correct value of `Australia Post Parcel Post`, so something is clearly an issue here - likely with Commerce again. 

But the amount is certainly being applied to the order, and is there once paid.

**Comment by angieherrera** [comment]
Strange - neither are working for me using the Commerce example templates. I'll get in touch with Craft. Thanks for taking a look!
